# Generated by Django 5.0b1 on 2023-11-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_contact_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
