# Generated by Django 5.0b1 on 2023-11-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
